version: 2.1

jobs:
  render-templates:
    machine: true
    steps:
      - checkout
      - run:
          name: Building from templates
          command: |
            make src
  build-and-push:
    machine: true
    steps:
      - run:
          name: Building and pushing image
          command:
            echo "Logging in to eu.gcr.io"
            docker login -u _json_key -p "$GCE_SA_JSON" https://eu.gcr.io

            echo "Building image"
            make image

            IMGTAG=eu.gcr.io/plum-infra/fluent/fluentd-kubernetes:$CIRCLE_BRANCH.$(git rev-parse --short HEAD)
            echo "Retagging image"
            docker tag fluent/fluentd-kubernetes:$VERSION $IMGTAG

            echo "Pushing image $IMGTAG"
            docker push $IMGTAG

workflows:
  version: 2
  render-build-and-push:
    jobs:
      - render-templates
      - build-and-push:
          requires:
            - render-templates
