version: 2.1

jobs:
  render-build-push:
    machine: true
    steps:
      - checkout
      - run:
          name: Build templates, image and push
          command: |
            make src

            echo "Logging in to eu.gcr.io"
            docker login -u _json_key -p "$GCE_SA_JSON" https://eu.gcr.io

            #pinning version of fluentd
            VERSION=v1.11.1-debian-elasticsearch7-1.3
            echo "Building image"
            make image

            IMGTAG=eu.gcr.io/plum-infra/fluent/fluentd-kubernetes:$CIRCLE_BRANCH.$(git rev-parse --short HEAD)
            echo "Retagging image"
            docker tag fluent/fluentd-kubernetes:$VERSION $IMGTAG

            echo "Pushing image $IMGTAG"
            docker push $IMGTAG

workflows:
  version: 2
  render-build-and-push:
    jobs:
      - render-build-push
